import csv
import os

def clean_decimal(value):
    """Replaces comma with dot and converts to float string."""
    if not value:
        return 'NULL'
    return value.replace(',', '.')

def escape_sql(value):
    """Escapes single quotes for SQL."""
    if not value:
        return 'NULL'
    return f"'{value.replace("'", "''")}'"

def main():
    input_file = 'maestro.csv'
    output_file = 'supabase/seed.sql'
    
    suertes_sql = []
    users_sql = []
    
    unique_tecnicos = set()
    unique_jefes = set()
    
    print(f"Reading from {input_file}...")
    
    try:
        with open(input_file, mode='r', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            
            for row in reader:
                # 1. Process Suertes
                suerte = escape_sql(row.get('SUERTE'))
                finca = escape_sql(row.get('FINCA'))
                zona = escape_sql(row.get('ZONA'))
                area = clean_decimal(row.get('AREA'))
                edad = clean_decimal(row.get('EDAD'))
                corte = escape_sql(row.get('NUMERO DE CORTE'))
                
                # Check for required fields to avoid garbage
                if suerte != 'NULL':
                     suertes_sql.append(f"INSERT INTO public.suertes (codigo, hacienda, zona, area_neta, edad, corte) VALUES ({suerte}, {finca}, {zona}, {area}, {edad}, {corte}) ON CONFLICT (codigo) DO UPDATE SET area_neta = EXCLUDED.area_neta, edad = EXCLUDED.edad, corte = EXCLUDED.corte;")

                # 2. Extract Users
                tecnico = row.get('TECNICO AGRICOLA RESPONSABLE')
                if tecnico:
                    unique_tecnicos.add(tecnico)
                    
                jefe = row.get('RESPONSABLE ZONA')
                if jefe:
                    unique_jefes.add(jefe)

    except FileNotFoundError:
        print(f"Error: {input_file} not found.")
        return

    # Generate User SQL (Mocking auth.users insertions for simplicity in seed, 
    # normally this is complex with auth schema, but for 'seed.sql' we often insert into public.usuarios directly 
    # OR we need to insert into auth.users first.
    # Given the prompt implies creating accounts, we'll generate SQL for public.usuarios 
    # AND a note about auth.users interaction or use a DO block to insert into auth.users if possible.
    # For a seed file, creating actual auth users via SQL is tricky without extension hacks.
    # We will generate IDs deterministically or randomly and insert into public.usuarios assuming the auth user 'exists' or just populate public.usuarios for development if RLS allows.
    # HOWEVER, the 'supabase-architect' skill defined public.usuarios with FK to auth.users.
    # So we MUST have auth users.
    # Strategy: Use a DO block to insert into auth.users if not exists, then public.usuarios.
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("-- Generated by Riopaila Seeder Skill\n")
        f.write("-- Source: maestro.csv\n\n")
        
        # User Generation Block
        f.write("-- ==========================================\n")
        f.write("-- 1. USERS (Tecnicos & Jefes)\n")
        f.write("-- ==========================================\n")
        
        all_users = []
        for u in unique_tecnicos:
            all_users.append({'name': u, 'role': 'tecnico'})
        for u in unique_jefes:
            all_users.append({'name': u, 'role': 'jefe_zona'})
            
        f.write("DO $$\nDECLARE\n  new_id uuid;\nBEGIN\n")
        
        for user in all_users:
            name = user['name']
            role = user['role']
            email = f"{name.replace(' ', '.').lower()}@riopaila.com"
            escaped_name = name.replace("'", "''")
            
            f.write(f"  -- User: {name} ({role})\n")
            f.write(f"  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = '{email}') THEN\n")
            f.write(f"    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) VALUES (gen_random_uuid(), '{email}', crypt('Riopaila2026', gen_salt('bf')), now(), '{{\"provider\": \"email\", \"providers\": [\"email\"]}}', '{{\"nombre\": \"{escaped_name}\"}}', 'authenticated', 'authenticated') RETURNING id INTO new_id;\n")
            f.write(f"    INSERT INTO public.usuarios (id, email, nombre, rol) VALUES (new_id, '{email}', '{escaped_name}', '{role}');\n")
            f.write(f"  END IF;\n\n")
            
        f.write("END $$;\n\n")

        # Suertes Generation Block
        f.write("-- ==========================================\n")
        f.write("-- 2. SUERTES\n")
        f.write("-- ==========================================\n")
        for statement in suertes_sql:
            f.write(statement + "\n")
            
        # Maquinaria Generic Block
        f.write("\n-- ==========================================\n")
        f.write("-- 3. MAQUINARIA GENERIC\n")
        f.write("-- ==========================================\n")
        f.write("INSERT INTO public.maquinaria (codigo, nombre, tipo, estado) VALUES \n")
        f.write("('TR-001', 'John Deere 5075E', 'Tractor', 'ACTIVO'),\n")
        f.write("('TR-002', 'Massey Ferguson 4700', 'Tractor', 'ACTIVO'),\n")
        f.write("('CS-001', 'Case IH Austoft 9000', 'Cosechadora', 'ACTIVO')\n")
        f.write("ON CONFLICT (codigo) DO NOTHING;\n")

        # Labores Generic Block
        f.write("\n-- ==========================================\n")
        f.write("-- 4. LABORES GENERIC\n")
        f.write("-- ==========================================\n")
        f.write("INSERT INTO public.labores (nombre, descripcion) VALUES \n")
        f.write("('Preparación Suelo', 'Adecuación de terreno para siembra'),\n")
        f.write("('Siembra', 'Siembra de caña'),\n")
        f.write("('Cosecha', 'Corte y alce'),\n")
        f.write("('Fertilización', 'Aplicación de insumos')\n")
        f.write("ON CONFLICT (nombre) DO NOTHING;\n")
        
    print(f"Successfully generated {output_file} with {len(suertes_sql)} suertes and {len(all_users)} users.")

if __name__ == '__main__':
    main()
