-- Generated by Riopaila Seeder Skill
-- Source: maestro.csv

-- ==========================================
-- 1. USERS (Tecnicos & Jefes)
-- ==========================================
DO $$
DECLARE
  new_id uuid;
BEGIN
  -- User: Juan Perez (tecnico)
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'juan.perez@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) VALUES (gen_random_uuid(), 'juan.perez@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Juan Perez"}', 'authenticated', 'authenticated') RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, email, nombre, rol) VALUES (new_id, 'juan.perez@riopaila.com', 'Juan Perez', 'tecnico');
  END IF;

  -- User: Maria Gomez (tecnico)
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'maria.gomez@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) VALUES (gen_random_uuid(), 'maria.gomez@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Maria Gomez"}', 'authenticated', 'authenticated') RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, email, nombre, rol) VALUES (new_id, 'maria.gomez@riopaila.com', 'Maria Gomez', 'tecnico');
  END IF;

  -- User: Carlos Jefe (jefe_zona)
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'carlos.jefe@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) VALUES (gen_random_uuid(), 'carlos.jefe@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Carlos Jefe"}', 'authenticated', 'authenticated') RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, email, nombre, rol) VALUES (new_id, 'carlos.jefe@riopaila.com', 'Carlos Jefe', 'jefe_zona');
  END IF;

  -- User: Ana Jefa (jefe_zona)
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'ana.jefa@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) VALUES (gen_random_uuid(), 'ana.jefa@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Ana Jefa"}', 'authenticated', 'authenticated') RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, email, nombre, rol) VALUES (new_id, 'ana.jefa@riopaila.com', 'Ana Jefa', 'jefe_zona');
  END IF;

END $$;

-- ==========================================
-- 2. SUERTES
-- ==========================================
INSERT INTO public.suertes (codigo, hacienda, zona, area_neta, edad, corte) VALUES ('101', 'Hacienda La Gloria', 'Norte', 10.5, 2.5, '1') ON CONFLICT (codigo) DO UPDATE SET area_neta = EXCLUDED.area_neta, edad = EXCLUDED.edad, corte = EXCLUDED.corte;
INSERT INTO public.suertes (codigo, hacienda, zona, area_neta, edad, corte) VALUES ('102', 'Hacienda El Triunfo', 'Sur', 8.2, 1.0, '2') ON CONFLICT (codigo) DO UPDATE SET area_neta = EXCLUDED.area_neta, edad = EXCLUDED.edad, corte = EXCLUDED.corte;
INSERT INTO public.suertes (codigo, hacienda, zona, area_neta, edad, corte) VALUES ('103', 'Hacienda La Gloria', 'Norte', 15.0, 4.5, '1') ON CONFLICT (codigo) DO UPDATE SET area_neta = EXCLUDED.area_neta, edad = EXCLUDED.edad, corte = EXCLUDED.corte;

-- ==========================================
-- 3. MAQUINARIA GENERIC
-- ==========================================
INSERT INTO public.maquinaria (codigo, nombre, tipo, estado) VALUES 
('TR-001', 'John Deere 5075E', 'Tractor', 'ACTIVO'),
('TR-002', 'Massey Ferguson 4700', 'Tractor', 'ACTIVO'),
('CS-001', 'Case IH Austoft 9000', 'Cosechadora', 'ACTIVO')
ON CONFLICT (codigo) DO NOTHING;

-- ==========================================
-- 4. LABORES GENERIC
-- ==========================================
INSERT INTO public.labores (nombre, descripcion) VALUES 
('Preparación Suelo', 'Adecuación de terreno para siembra'),
('Siembra', 'Siembra de caña'),
('Cosecha', 'Corte y alce'),
('Fertilización', 'Aplicación de insumos')
ON CONFLICT (nombre) DO NOTHING;
