-- Generated by Antigravity (Riopaila Seeder Fixed)
DO $$
DECLARE
  new_id uuid;
  contratista_id uuid;
BEGIN
  -- ==========================================
  -- 1. USERS
  -- ==========================================
  
  -- Tecnico: Juan Perez
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'juan.perez@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) 
    VALUES (gen_random_uuid(), 'juan.perez@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Juan Perez"}', 'authenticated', 'authenticated') 
    RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, nombre, rol) VALUES (new_id, 'Juan Perez', 'tecnico');
  END IF;

  -- Tecnico: Maria Gomez
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'maria.gomez@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) 
    VALUES (gen_random_uuid(), 'maria.gomez@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Maria Gomez"}', 'authenticated', 'authenticated') 
    RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, nombre, rol) VALUES (new_id, 'Maria Gomez', 'tecnico');
  END IF;

  -- Jefe Zona: Carlos Jefe
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'carlos.jefe@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) 
    VALUES (gen_random_uuid(), 'carlos.jefe@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Carlos Jefe"}', 'authenticated', 'authenticated') 
    RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, nombre, rol) VALUES (new_id, 'Carlos Jefe', 'jefe_zona');
  END IF;

  -- Jefe Zona: Ana Jefa
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'ana.jefa@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) 
    VALUES (gen_random_uuid(), 'ana.jefa@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Ana Jefa"}', 'authenticated', 'authenticated') 
    RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, nombre, rol) VALUES (new_id, 'Ana Jefa', 'jefe_zona');
  END IF;

  -- Analista: Pedro Analista
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'pedro.analista@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) 
    VALUES (gen_random_uuid(), 'pedro.analista@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Pedro Analista"}', 'authenticated', 'authenticated') 
    RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, nombre, rol) VALUES (new_id, 'Pedro Analista', 'analista');
  END IF;

  -- Operador: Hugo Operador
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'hugo.operador@riopaila.com') THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role) 
    VALUES (gen_random_uuid(), 'hugo.operador@riopaila.com', crypt('Riopaila2026', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"nombre": "Hugo Operador"}', 'authenticated', 'authenticated') 
    RETURNING id INTO new_id;
    INSERT INTO public.usuarios (id, nombre, rol) VALUES (new_id, 'Hugo Operador', 'operador');
  END IF;

  -- ==========================================
  -- 2. CONTRATISTAS & MAQUINARIA
  -- ==========================================
  
  -- Insert Generic Contractor safely
  SELECT id INTO contratista_id FROM public.contratistas WHERE nombre = 'Agrícola Riopaila S.A.S.';
  
  IF contratista_id IS NULL THEN
    INSERT INTO public.contratistas (nombre) VALUES ('Agrícola Riopaila S.A.S.') RETURNING id INTO contratista_id;
  END IF;

  -- Insert Machinery linked to Contractor
  IF NOT EXISTS (SELECT 1 FROM public.maquinaria WHERE nombre = 'John Deere 5075E') THEN
    INSERT INTO public.maquinaria (nombre, tarifa_hora, contratista_id) VALUES ('John Deere 5075E', 120000, contratista_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.maquinaria WHERE nombre = 'Massey Ferguson 4700') THEN
    INSERT INTO public.maquinaria (nombre, tarifa_hora, contratista_id) VALUES ('Massey Ferguson 4700', 115000, contratista_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.maquinaria WHERE nombre = 'Case IH Austoft 9000') THEN
    INSERT INTO public.maquinaria (nombre, tarifa_hora, contratista_id) VALUES ('Case IH Austoft 9000', 450000, contratista_id);
  END IF;

  -- ==========================================
  -- 3. LABORES
  -- ==========================================
  IF NOT EXISTS (SELECT 1 FROM public.labores WHERE nombre = 'Preparación Suelo') THEN
    INSERT INTO public.labores (nombre, descripcion) VALUES ('Preparación Suelo', 'Adecuación de terreno para siembra');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM public.labores WHERE nombre = 'Siembra') THEN
    INSERT INTO public.labores (nombre, descripcion) VALUES ('Siembra', 'Siembra de caña');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM public.labores WHERE nombre = 'Cosecha') THEN
    INSERT INTO public.labores (nombre, descripcion) VALUES ('Cosecha', 'Corte y alce mecanizado');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.labores WHERE nombre = 'Fertilización') THEN
    INSERT INTO public.labores (nombre, descripcion) VALUES ('Fertilización', 'Aplicación de insumos');
  END IF;

  -- ==========================================
  -- 4. SUERTES (Fixed Types)
  -- ==========================================
  INSERT INTO public.suertes (codigo, hacienda, zona, area_neta, edad, corte, tecnico_responsable_nombre, responsable_zona_nombre) 
  VALUES ('101', 'Hacienda La Gloria', 1, 10.5, 2.5, 1, 'Juan Perez', 'Carlos Jefe') 
  ON CONFLICT (codigo) DO UPDATE SET area_neta = EXCLUDED.area_neta, edad = EXCLUDED.edad, corte = EXCLUDED.corte, tecnico_responsable_nombre = EXCLUDED.tecnico_responsable_nombre, responsable_zona_nombre = EXCLUDED.responsable_zona_nombre;

  INSERT INTO public.suertes (codigo, hacienda, zona, area_neta, edad, corte, tecnico_responsable_nombre, responsable_zona_nombre) 
  VALUES ('102', 'Hacienda El Triunfo', 2, 8.2, 1.0, 2, 'Maria Gomez', 'Ana Jefa') 
  ON CONFLICT (codigo) DO UPDATE SET area_neta = EXCLUDED.area_neta, edad = EXCLUDED.edad, corte = EXCLUDED.corte, tecnico_responsable_nombre = EXCLUDED.tecnico_responsable_nombre, responsable_zona_nombre = EXCLUDED.responsable_zona_nombre;

  INSERT INTO public.suertes (codigo, hacienda, zona, area_neta, edad, corte, tecnico_responsable_nombre, responsable_zona_nombre) 
  VALUES ('103', 'Hacienda La Gloria', 1, 15.0, 4.5, 1, 'Juan Perez', 'Carlos Jefe') 
  ON CONFLICT (codigo) DO UPDATE SET area_neta = EXCLUDED.area_neta, edad = EXCLUDED.edad, corte = EXCLUDED.corte, tecnico_responsable_nombre = EXCLUDED.tecnico_responsable_nombre, responsable_zona_nombre = EXCLUDED.responsable_zona_nombre;

END $$;
