-- Insert contractors if they don't exist
INSERT INTO public.contratistas (nombre)
VALUES 
    ('AGROVASCAS S A S'),
    ('SERVICIOS AGROMECANICOS DE OCCIDENTES S.A.S.'),
    ('SERVICIOS AGRICOLAS VARGAS S.A.S'),
    ('ANDRUSV S A S'),
    ('AGROMAQUINARIA GALVIL S.A.S'),
    ('LABORES AGRICOLAS ROMERO S.A.S.'),
    ('RIOPAILA CASTILLA S.A'),
    ('BIENES Y MAQUINARIA SAS'),
    ('SERVI AGRICOLAS DIAGO S.A.S.'),
    ('AGROPECAM APOYO PARA EL CAMPO S.A.S.')
ON CONFLICT (nombre) DO NOTHING;
